# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Classes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
